
defaults:
  - _self_
  - task: branin
  - search_space: branin
  - target_function: branin
  - override hydra/sweeper: HyperCARPS

hydra:
  sweeper:
    n_trials: ${task.resource_kwargs.n_trials}
    search_space: ${search_space}
    sweeper_kwargs:
      optimizer_kwargs:
        optimizer: 
          _target_: carps.optimizers.smac20.SMAC3Optimizer
          _partial_: true
        task: ${task}
        optimizer_cfg:
          smac_class: smac.facade.blackbox_facade.BlackBoxFacade
          scenario:
            seed: 0
            n_trials: ${task.resource_kwargs.n_trials}
            objectives: ${task.output_kwargs.objectives}
            deterministic: true
            n_workers: 1
            output_directory: ${hydra.sweep.dir}
            min_budget: ${task.fidelity_kwargs.min_fidelity}
            max_budget: ${task.fidelity_kwargs.max_fidelity}
          smac_kwargs:
            dask_client: null
            overwrite: true
  run:
    dir: ./tmp/branin_carps_smac/
  sweep:
    dir: ./tmp/branin_carps_smac/