
defaults:
  - _self_
  - target_function: branin
  - task: branin
  - search_space: branin
  - override hydra/sweeper: HyperCARPS

hydra:
  sweeper:
    n_trials: 15
    sweeper_kwargs:
      optimizer_kwargs:
        optimizer:
          _target_: carps.optimizers.hebo.HEBOOptimizer
          _partial_: true
        task_config: ${task}
    search_space: ${search_space}
  run:
    dir: ./tmp/branin_carps_hebo/
  sweep:
    dir: ./tmp/branin_carps_hebo/