
defaults:
  - _self_
  - target_function: mlp
  - search_space: mlp_no_conditions
  - override hydra/sweeper: HyperLPI

hydra:
  sweeper:
    n_trials: 100
    sweeper_kwargs:
      max_budget: 100
      optimizer_kwargs:
        config:
          n_layer: 1
          n_neurons: 8
          activation: logistic
          solver: lbfgs
          batch_size: 30
          learning_rate: constant
          learning_rate_init: 1.0
        configs_per_hp: 20
        run_source: True
    search_space: ${search_space}
  run:
    dir: ./tmp/mlp_lpi/
  sweep:
    dir: ./tmp/mlp_lpi/
