fidelity_kwargs:
  is_multifidelity: true
  fidelity_type: epochs
  min_fidelity: 5
  max_fidelity: 50
output_kwargs:
  n_objectives: 1
  objectives:
  - accuracy
resource_kwargs:
  n_trials: 15
  time_budget: null
  n_workers: 1
metadata_kwargs:
  has_constraints: false
  domain: synthetic
  objective_function_approximation: real
  has_virtual_time: false
  deterministic: true
  dimensions: 1
  search_space_n_categoricals: 0
  search_space_n_ordinals: 0
  search_space_n_integers: 0
  search_space_n_floats: 1
  search_space_has_conditionals: false
  search_space_has_forbiddens: false
  search_space_has_priors: false